### ISSUE TITLE
Please review my Week 5 assignment code

### ISSUE THREAD

**Issue by jshandling77** [rin3-spring-2021/NBA-DFS-Project#1]
I will be cleaning this data up further as we go along but I felt that this code and chart were a good start.

Thanks for reviewing it for me.

Jeff

**Comment by charliejhadley** [comment]
Hi @jshandling77 unfortunately I can't get the code to work on my machine.

At the moment you've hardcoded the filepath for your data

```r
read_csv("~/Desktop/NBA_DFS_Master.csv")
```

Could you do the following:

- move your data file into the RStudio project folder (i.e. this repo on your local machine)
- push the updates
- tag me in a new comment when it's ready

**Comment by charliejhadley** [comment]
@jshandling77 here's my feedback video - https://share.getcloudapp.com/8Lubk8vX.

I get lost in weeds trying to understand what your intent is with this code

```r
dfs_master_zero <- dfs_master[apply(dfs_master, 1, function(row) all(row !=0 )), ]
```

What are you intending for this code to do?

**Comment by jshandling77** [comment]
Hi Charlie-

I apologize for this. That is some code that I was trying something with
and forgot to edit out. I will clean this stuff up and send you a cleaner
version once I've worked on it some more over the next week. You'll be able
to see a better version once I'm done with this coming week's assignment.

Thank you for your help.

Jeff
