### ISSUE TITLE
Please my code for Week 6

### ISSUE THREAD

**Issue by jshandling77** [rin3-spring-2021/NBA-DFS-Project#3]
Hi Charlie-

Please review my Points Per Minute Analysis file. I appreciate any feedback you may have.

Thank you
Jeff

**Comment by charliejhadley** [comment]
Thanks @jshandling77 ! The code's looking good, here's my feedback https://share.getcloudapp.com/Jru4ONld

**Comment by jshandling77** [comment]
Thanks Charlie for the feedback. I know my code is a little long and not
super clean style-wise but as I get further along, I'm sure I'll be able to
start putting lines together more seamlessly.

Have a great day!

Jeff
