### ISSUE TITLE
Please review my week 7 code

### ISSUE THREAD

**Issue by jshandling77** [rin3-spring-2021/NBA-DFS-Project#4]
Hi Charlie-

Please take a look at my code for this week. I changed up the parameters to look at points per salary versus points per minute. I then wanted to take the chart I made and highlight the salaries where the point per salary was greater than or equal to 5. I didn't know how to make those values a different fill color.

Thanks for the help
Jeff

**Comment by charliejhadley** [comment]
Hey @jshandling77 unfortunately I think you might have forgotten to commit a script file? Or else I didn't understand your code.
But I made an example of how to conditionally colour a ggplot2 chart https://share.getcloudapp.com/rRuGzLkZ
