### ISSUE TITLE
R Script File for Week 7

### ISSUE THREAD

**Issue by jshandling77** [rin3-spring-2021/NBA-DFS-Project#5]
Hi Charlie-

My apologies for forgetting to get you the r script file. You should be able to review it now. And thank you for the little video on the conditional charting.

Jeff

**Comment by charliejhadley** [comment]
No worries! Folks on other projects I work on forget to push all the time 😀

Here's my feedback https://share.getcloudapp.com/o0u6K4Gn

**Comment by jshandling77** [comment]
Thanks Charlie for the feedback. It's much appreciated. One, last question,
let's say I wanted to group the sum of a number between a bunch of ranges
of a number. For example, in my code, what if I wanted the total points for
salaries between 3.0-3.9, 4.0-4.9, etc? I tried to use a case_when but I
don't think you can do that with dbl's. Any idea how I might make this work?

Thanks
Jeff

**Comment by charliejhadley** [comment]
Hi @jshandling77 sorry I can't replicate this issue.

Here's a minimal example that's hopefully useful 

```r
library("tidyverse")

set.seed(20)
tibble(points_per_salary = rnorm(100, mean = 4, sd = 1.5)) %>%
  mutate(
    range_points_per_salary = case_when(
      points_per_salary < 0 ~ "Negative",
      0 < points_per_salary & points_per_salary < 3 ~ "Very small",
      3 < points_per_salary & points_per_salary < 4 ~ "Medium",
      TRUE ~ "Large"
    )
  )

```
