### ISSUE TITLE
Week 8 Project Update

### ISSUE THREAD

**Issue by jshandling77** [rin3-spring-2021/NBA-DFS-Project#6]
Hi Charlie-

My apologies for getting my project in late this week. I updated the project with getting a new master data set to improve the accuracy of my results. I decided to look at if projected points vs actual points was linear based on salary. My graph is not exactly how I'd like it as I would have preferred to have the coord_flip show the "outperform" in descending order by salary. I couldn't get that to quite work.

Thanks
Jeff

**Comment by charliejhadley** [comment]
Hi @jshandling77 I wasn't entirely sure what you meant by ordering only the "outperform" by salary. Could you let me know if this solves your need or not https://share.getcloudapp.com/p9ubqLgK ?

**Comment by jshandling77** [comment]
Charlie-

My apologies for not being clear. I want the y axis to descend by the
percent_fire so it would look like below: Salary on the y and percent_fire
on the x. Hope this helps. I kept getting errors saying I can't reorder
using continuous data.

[image: Code Issue.png]

**Comment by charliejhadley** [comment]
Sorry @jshandling77  the image didn't come through

**Comment by jshandling77** [comment]
Can you see the attachment now?

**Comment by charliejhadley** [comment]
Sorry @jshandling77 it's still not showing. When you write the comment check if the attachment appears in the "Preview"

**Comment by jshandling77** [comment]
Charlie-

I'm still getting used to using GitHub. I believe you'll be able to see what I'm looking for in my chart. 


<img width="399" alt="Code Issue" src="https://user-images.githubusercontent.com/12661750/118414787-35c8b000-b66c-11eb-8a6b-8c53e7bbd2d1.png">

**Comment by charliejhadley** [comment]
No worries about GitHub being new - it's all very new. I think I'm failing to understand exactly what you'd like - as I say in the video, please draw me a version of the chart you'd like if this doesn't solve the issue https://share.getcloudapp.com/yAuDODGl

**Comment by jshandling77** [comment]
This is a pretty bad drawing but maybe this will help? I feel like it has something to do with the fact that I cannot reorder continuous data. Lets keep trying. Thanks for your help.



<img width="768" alt="code example" src="https://user-images.githubusercontent.com/12661750/118710856-79dec080-b7e4-11eb-889a-d3be3cce4354.png">

**Comment by charliejhadley** [comment]
Thanks @jshandling77! Here's a a video explaining how I made this chart https://share.rfor.us/Blu4n9kz

```r

proj_vs_act1 %>% 
  mutate(salary_chr = as.character(salary)) %>% 
  mutate(salary_chr = fct_reorder(salary_chr, percent_fire)) %>% 
  ggplot(aes(x = percent_fire,
             y = salary_chr)) +
  geom_col() +
  geom_text(aes(x = ifelse(percent_fire > 0.05, percent_fire - 0.01, percent_fire + 0.01),
                label = salary_chr),
            size = 2.5) +
  scale_x_continuous(expand = c(0, 0)) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
```

![image](https://user-images.githubusercontent.com/9363263/118977633-4891fc00-b96e-11eb-9cf9-57871c7f2e17.png)

**Comment by jshandling77** [comment]
Thanks Charlie! This was extremely helpful. Much appreciated.
